import type { ReactNode } from 'react'
import { Feather } from '@expo/vector-icons'
import { ActivityIndicator, Image, Modal, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View, type TextInputProps } from 'react-native'

export const colors = { bg: '#F5F6F8', white: '#FFFFFF', text: '#193A38', muted: '#536761', green: '#008744', border: '#E2E6EA', soft: '#EDF9F2', error: '#A42C30' }
export const s = StyleSheet.create({
  flex: { flex: 1 }, page: { padding: 18, paddingBottom: 30, gap: 14, width: '100%', maxWidth: 700, alignSelf: 'center' },
  card: { backgroundColor: colors.white, borderRadius: 16, padding: 16, borderWidth: 1, borderColor: colors.border, gap: 10 },
  row: { flexDirection: 'row', alignItems: 'center', gap: 10, flexWrap: 'wrap' }, between: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 10, flexWrap: 'wrap' },
  title: { color: colors.text, fontSize: 17, fontWeight: '700' }, text: { color: colors.text, fontSize: 14, lineHeight: 21 }, muted: { color: colors.muted, fontSize: 13, lineHeight: 20 },
  label: { color: colors.text, fontSize: 13, fontWeight: '600', marginBottom: 6 }, input: { borderWidth: 1, borderColor: colors.border, borderRadius: 11, paddingHorizontal: 13, paddingVertical: 12, minHeight: 48, color: colors.text, backgroundColor: colors.white, fontSize: 16 },
  error: { color: colors.error, backgroundColor: '#FFF1F1', borderRadius: 10, padding: 12, fontSize: 13, lineHeight: 20 },
  separator: { height: 1, backgroundColor: colors.border, marginVertical: 4 },
  header: { backgroundColor: colors.white, borderBottomWidth: 1, borderBottomColor: colors.border, paddingHorizontal: 18, paddingVertical: 12, flexDirection: 'row', alignItems: 'center', gap: 10 },
  heading: { color: colors.text, fontSize: 22, fontWeight: '800', flexShrink: 1 }, logo: { width: 110, height: 46 },
  button: { minHeight: 46, borderRadius: 11, backgroundColor: colors.green, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8, paddingVertical: 11, paddingHorizontal: 15 },
  secondary: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border }, buttonText: { color: colors.white, fontSize: 14, fontWeight: '700' },
  badge: { backgroundColor: colors.soft, paddingHorizontal: 10, paddingVertical: 5, borderRadius: 20, alignSelf: 'flex-start' }, badgeText: { color: colors.green, fontSize: 12, fontWeight: '600' },
  overlay: { flex: 1, backgroundColor: '#142B2666', justifyContent: 'flex-end' }, sheet: { backgroundColor: colors.bg, borderTopLeftRadius: 24, borderTopRightRadius: 24, maxHeight: '90%', paddingBottom: 20 },
})
export function Logo({ large = false }: { large?: boolean }) { return <Image source={require('../../assets/logo.png')} resizeMode="contain" accessibilityLabel="Call Labs" style={large ? { width: 230, height: 100, alignSelf: 'center' } : s.logo} /> }
export function Header({ title, onBack }: { title: string; onBack?: () => void }) { return <View style={s.header}>{onBack && <Pressable onPress={onBack} accessibilityRole="button" accessibilityLabel="Go back" style={{ padding: 8, minHeight: 44, justifyContent: 'center' }}><Feather name="arrow-left" size={23} color={colors.text} /></Pressable>}<Text accessibilityRole="header" style={[s.heading, { flex: 1 }]}>{title}</Text><Logo /></View> }
export function Button({ label, onPress, secondary = false, busy = false, disabled = false, icon }: { label: string; onPress: () => void; secondary?: boolean; busy?: boolean; disabled?: boolean; icon?: React.ComponentProps<typeof Feather>['name'] }) {
  return <Pressable accessibilityRole="button" accessibilityState={{ disabled: busy || disabled, busy }} onPress={onPress} disabled={busy || disabled} style={({ pressed }) => [s.button, secondary && s.secondary, { opacity: busy || disabled ? .5 : pressed ? .8 : 1 }]}>{busy ? <ActivityIndicator color={secondary ? colors.green : colors.white} /> : icon ? <Feather name={icon} size={18} color={secondary ? colors.green : colors.white} /> : null}<Text style={[s.buttonText, secondary && { color: colors.green }]}>{label}</Text></Pressable>
}
export function Field({ label, ...props }: TextInputProps & { label: string }) { return <View><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} placeholderTextColor={colors.muted} {...props} style={[s.input, props.multiline && { minHeight: 90, textAlignVertical: 'top' }, props.style]} /></View> }
export function Badge({ label }: { label: string }) { return <View style={s.badge}><Text style={s.badgeText}>{label}</Text></View> }
export function ErrorNotice({ error }: { error?: string }) { return error ? <Text accessibilityLiveRegion="polite" style={s.error}>{error}</Text> : null }
export function Page({ children, refreshing = false, onRefresh }: { children: ReactNode; refreshing?: boolean; onRefresh?: () => void }) { return <ScrollView style={s.flex} contentContainerStyle={s.page} keyboardShouldPersistTaps="handled" keyboardDismissMode="on-drag" refreshControl={onRefresh ? <RefreshControl refreshing={refreshing} onRefresh={onRefresh} tintColor={colors.green} colors={[colors.green]} /> : undefined}>{children}</ScrollView> }
export function Loading({ label = 'Loading your workspace…' }: { label?: string }) { return <View style={{ padding: 24, alignItems: 'center', gap: 10 }}><ActivityIndicator color={colors.green} /><Text style={s.muted}>{label}</Text></View> }
export function Empty({ title, detail }: { title: string; detail: string }) { return <View style={[s.card, { paddingVertical: 30, alignItems: 'center' }]}><Feather name="inbox" color={colors.green} size={28} /><Text style={s.title}>{title}</Text><Text style={[s.muted, { textAlign: 'center' }]}>{detail}</Text></View> }
export function Picker({ label, value, options, onChange, open, onToggle }: { label: string; value: string; options: { value: string; label: string }[]; onChange: (value: string) => void; open: boolean; onToggle: () => void }) {
  return <View><Text style={s.label}>{label}</Text><Pressable accessibilityRole="button" accessibilityLabel={label} accessibilityState={{ expanded: open }} onPress={onToggle} style={[s.input, s.between]}><Text style={s.text}>{options.find(o => o.value === value)?.label || 'Select'}</Text><Feather name="chevron-down" color={colors.green} size={18} /></Pressable>{open && <View style={[s.card, { marginTop: 6 }]}>{options.map(o => <Pressable key={o.value} onPress={() => onChange(o.value)} style={[s.row, { paddingVertical: 10, minHeight: 44 }]}><Feather name={o.value === value ? 'check-circle' : 'circle'} size={18} color={colors.green} /><Text style={[s.text, { flex: 1 }]}>{o.label}</Text></Pressable>)}</View>}</View>
}
export function Sheet({ title, visible, onClose, children }: { title: string; visible: boolean; onClose: () => void; children: ReactNode }) { return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={s.overlay}><View style={s.sheet}><View style={s.header}><Text style={[s.title, { flex: 1 }]}>{title}</Text><Pressable accessibilityRole="button" accessibilityLabel="Close" onPress={onClose} style={{ padding: 10 }}><Feather name="x" size={22} color={colors.text} /></Pressable></View><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.page}>{children}</ScrollView></View></View></Modal> }
export function Pagination({ page, count, onChange }: { page: number; count: number; onChange: (p: number) => void }) { return count > 1 ? <View style={s.between}><Button label="Previous" secondary disabled={page <= 1} onPress={() => onChange(page - 1)} /><Text style={s.muted}>Page {page} of {count}</Text><Button label="Next" secondary disabled={page >= count} onPress={() => onChange(page + 1)} /></View> : null }
